### ISSUE TITLE
Não carrega o CPF do cliente

### ISSUE THREAD

**Issue by lmarquine** [wvelludo/whmcs-boleto-facil#2]
O campo personalizado foi criado e configurado no módulo de pagamento, entretanto ao gerar o boleto acusa erro que não carregou o número do CPF

**Comment by wvelludo** [comment]
Irmaquine, na configuração do modulo você precisa definir qual o campo custom do whmcs que tem o cpf/cnpj para que o módulo use na hora de gerar o boleto.

**Comment by lmarquine** [comment]
Bom dia Wevwerton, obrigado pelo retorno, então, eu criei o campo
personalizado, conforme a figura.

[image: Inline images 2]
[image: Inline images 3]
Ficou com o ID customfield5, mas mesmo usando ele ou o Friendly name, o
erro continua, eu usei o log console e o valor do CPF não está sendo
enviado na URL, será que é algo no WHMCS? Uso a versão 7.2

Leonardo Marquine Pereira
+55 19 988553580
lmarquine@gmail.com

2017-09-18 9:53 GMT-03:00 Weverton Velludo <notifications@github.com>:

**Comment by wvelludo** [comment]
No módulo eu pego o parametro "campocpf" (Campo CPF/CNPJ)  que vem da configuração transformo na variavel "$doc" e mando como parâmetro depois na requisicao do webservice
 rawurlencode($params['clientdetails'][$doc])

Tenta dar um print_r($params); para confirmar como está chegando o nome do campo la no módulo, pode colocar na linha 32.

**Comment by lmarquine** [comment]
Opa, deu certo, na fatura tá puxando customfields1 e aparece na fatura,
agora tá dando certo :D

[image: Inline images 1]
Estranho porque clicando com o botão direito no campo nos dados dos
clientes aparece no id customfield5, enfim, cara muitoooo obrigado, pela
contribuição com o módulo e com a atenção pra me ajudar.

Leonardo Marquine Pereira
+55 19 988553580
lmarquine@gmail.com

2017-09-18 10:56 GMT-03:00 Weverton Velludo <notifications@github.com>:
